#!/bin/bash

set -e

topd=$(pwd)
tstamp=$(date +%Y-%m-%d_%H-%M-%S)
outdir="${topd}/work-${tstamp}"
indir="${topd}/src"
hdir="/home/docker"

mkdir ${outdir}
chmod 757 ${outdir}
docker run -v ${indir}:${hdir}/src:ro \
       -v ${outdir}:${hdir}/work \
       -w ${hdir}/work \
       --user docker \
       eamon/2017reporting:v20171211 /bin/bash -c \
       "cp ../src/*.R . && cp ../src/Makefile . && make"
chown -R --reference $0 ${outdir}
chmod 755 ${outdir}
