#!/bin/bash

set -e

topd=$(pwd)
tstamp=$(date +%Y-%m-%d_%H-%M-%S)
outdir="${topd}/work-${tstamp}"
indir="${topd}/src"
hdir="/home/docker"

mkdir ${outdir}
chmod 757 ${outdir}
function finish {
    chown -R --reference $0 ${outdir}
    chmod 755 ${outdir}
}
trap finish EXIT

docker run -v ${indir}:${hdir}/src:ro \
       -v ${outdir}:${hdir}/work \
       -w ${hdir}/work \
       --user docker \
       eamon/2017reporting:20171212 /bin/bash -c \
       "cp ../src/*.R . && cp ../src/Makefile . && ln -s ../packrat && cp ../.Rprofile . && make"
